#  Service
apiVersion: v1
kind: Service
metadata:
  name: k8s-test-app
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: k8s-test-app

# Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-test-app
  template:
    metadata:
      labels:
        app: k8s-test-app
    spec:
      containers:
      - name: k8s-test-app
        image: islamicnetwork/k8s-deployment:$COMMIT_TAG
        resources:
          requests:
            memory: "16Mi"
          limits:
            memory: "128Mi"
        ports:
        - containerPort: 8080
          protocol: TCP
